apiVersion: v1
kind: Pod
metadata:
  name: ${PROVISIONER_NAME}
  namespace: ${NAMESPACE}
spec:
  containers:
  - command:
    - /storage-provisioner
    image: ${PROVISIONER_IMAGE}
    imagePullPolicy: IfNotPresent
    name: ${PROVISIONER_NAME}
    volumeMounts:
    - mountPath: /tmp
      name: storage-provisioner-path
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: storage-provisioner-token
      readOnly: true
  serviceAccount: ${ACCOUNT_NAME}
  serviceAccountName: ${ACCOUNT_NAME}
  terminationGracePeriodSeconds: 30
  volumes:
  - hostPath:
      path: ${STORAGE_PATH}
      type: Directory
    name: storage-provisioner-path
  - name: storage-provisioner-token
    secret:
      defaultMode: 420
      secretName: ${ACCOUNT_TOKEN}
