apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-${STORAGE_NAME}-pvc
spec:
  storageClassName: ${STORAGE_NAME}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
